TERMINAL=foot
EDITOR=nvim
VIRTUAL=nvim
RUSTUP_DIST_SERVER=https://rsproxy.cn
RUSTUP_UPDATE_ROOT=https://rsproxy.cn/rustup
QT_QPA_PLATFORMTHEME=gtk3
QT_QPA_PLATFORMTHEME_QT6=gtk3
ELECTRON_OZONE_PLATFORM_HINT=auto
XCURSOR_THEME=catppuccin-mocha-light-cursors
XCURSOR_SIZE=24
