[Appearance]
standard_dialogs=default
style=Fusion

[Fonts]
fixed="MonoLisa,13,-1,5,50,0,0,0,0,0"
general="Inter,13,-1,5,50,0,0,0,0,0"
color_scheme_path=/usr/share/qt6ct/colors/catppuccin-latte-mauve.conf
custom_palette=true
icon_theme=Papirus-Light
